version: "3.7"
services:
  otpman-api:
    image: gndlovu/dev-env:latest
    container_name: otpman-api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html/
    ports:
      - "2000:80"
